2019-10-16 21:17:53,574 ERROR: Exception on / [GET] [in /Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/felipepoulsen/Documents/moneyball_app/app/routes.py", line 19, in index
    if current_user.is_authenticated:
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/Users/felipepoulsen/Documents/moneyball_app/app/models.py", line 163, in load_user
    return User.query.get(int(id))
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1069, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 282, in load_on_pk_identity
    return q.one()
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3292, in one
    ret = self.one_or_none()
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3261, in one_or_none
    ret = list(self)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3359, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/Users/felipepoulsen/anaconda3/envs/flask/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.shortname AS user_shortname, user.nickname AS user_nickname, user.password_hash AS user_password_hash, user.company_id AS user_company_id, user.is_admin AS user_is_admin 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/e3q8)
